import { NextResponse } from "next/server";
import { getRepository } from "@/lib/db";
import { runVerificationPipeline, getCachedVerificationResult } from "@/lib/verification-engine";

export async function POST(req: Request) {
  try {
    const {
      title,
      description,
      category,
      latitude,
      longitude,
      address,
      severity,
      anonymous,
      beforePhotoUrl,
      photoName,
      exifLat,
      exifLng,
      exifSoftware,
      createdById,
      verificationToken,
      sha256Hash
    } = await req.json();

    if (!title || !description || !category || !latitude || !longitude || !createdById) {
      return NextResponse.json(
        { message: "Missing required complaint submission parameters" },
        { status: 400 }
      );
    }

    try {
      const repo = getRepository();
      const userRes = await repo.getUserByEmail(createdById); // Wait, this expects ID not email! I need to use getUserId? Let's check how the user is queried.
      // Ah, wait, in existing code it's `SELECT id, role FROM users WHERE id = $1`, [createdById]
      // I should add getUserById to the repository. Let me just implement it later in repo, and use it here.
      // Let's add it to repo types: getUserById(id: string): Promise<User | null>;
      
      const user = await repo.getUserById(createdById);
      if (!user) {
        return NextResponse.json(
          { message: "Unauthorized: User session node not found" },
          { status: 401 }
        );
      }
      if (user.role !== "CITIZEN") {
        return NextResponse.json(
          { message: "Forbidden: Only citizens can submit complaints" },
          { status: 403 }
        );
      }
    } catch (dbError: any) {
      console.error("COMPLAINTS AUTH VALIDATION ERROR:", dbError.message);
      return NextResponse.json(
        { message: "Service temporarily unavailable. Please try again." },
        { status: 503 }
      );
    }

    // Safe server-side reuse of previously verified result (eliminates double pipeline execution)
    let verificationResult = (verificationToken ? getCachedVerificationResult(verificationToken) : null) ||
                            (sha256Hash ? getCachedVerificationResult(sha256Hash) : null);

    if (!verificationResult) {
      // Fallback: execute pipeline if not pre-verified or cache expired
      let fileBuffer: Buffer | undefined = undefined;
      let computedFileSize = 245000;
      if (beforePhotoUrl && beforePhotoUrl.startsWith("data:")) {
        const base64Data = beforePhotoUrl.split(",")[1];
        if (base64Data) {
          fileBuffer = Buffer.from(base64Data, "base64");
          computedFileSize = fileBuffer.length;
        }
      }

      verificationResult = await runVerificationPipeline({
        fileName: photoName || "evidence_photo.jpg",
        fileSize: computedFileSize,
        fileType: "image/jpeg",
        category,
        description,
        address,
        userLat: latitude,
        userLng: longitude,
        deviceLat: exifLat || latitude,
        deviceLng: exifLng || longitude,
        fileLastModified: Date.now(),
        fileData: fileBuffer,
        severity
      });
    }

    const trustScore = verificationResult.trustScore;
    const priorityPredicted = verificationResult.xaiReport.suggestedPriority || severity || "STANDARD";
    const explainableReport = verificationResult.xaiReport.summary;
    // Tracking ID is now securely generated by the database/repository.

    const duplicateDetected = verificationResult.isDuplicate;
    const duplicateParentId = verificationResult.duplicateLinkedId;
    const forgeryScore = verificationResult.manipulationDetected ? 85.0 : 0.0;
    let complaintId = "";
    try {
      const repo = getRepository();

      const newComplaint = await repo.createComplaint(
        {
          title,
          description,
          category,
          latitude,
          longitude,
          address: address || "Geocoded address",
          severity: priorityPredicted,
          anonymous: anonymous || false,
          before_photo_url: beforePhotoUrl || null,
          created_by_id: createdById,
          status: trustScore >= 60.0 ? "SUBMITTED" : "TPA_REVIEW"
        },
        undefined // evidence can be handled separately or added if needed. Wait, evidence was not inserted in the original? Ah, it was inserted in ai_reports but not evidence table in the original? Wait, let's look.
        // The original code did: INSERT INTO complaints... then INSERT INTO ai_reports... then INSERT INTO audit_logs. It didn't insert into evidence table!
      );

      complaintId = newComplaint.id;

      await repo.createAIReport({
        complaint_id: complaintId,
        exif_data: { exifLat, exifLng, exifSoftware },
        duplicate_detected: duplicateDetected,
        duplicate_parent_id: duplicateParentId,
        forgery_score: forgeryScore,
        trust_score: trustScore,
        explainable_report: explainableReport,
        priority_predicted: priorityPredicted,
        image_sha256: verificationResult.sha256Hash || null,
        image_phash: verificationResult.image_phash || null
      });

      await repo.createAuditLog({
        user_id: createdById,
        action: "SUBMIT_COMPLAINT",
        details: `Filed grievance ${newComplaint.tracking_id} with Trust Score: ${trustScore}%`
      });

      // Override trackingId with the real one generated by the repo
      var realTrackingId = newComplaint.tracking_id;

    } catch (dbError: any) {
      console.error("COMPLAINTS SUBMIT DATABASE ERROR:", dbError.message);
      return NextResponse.json(
        { message: "Database persistence failed" },
        { status: 503 }
      );
    }

    return NextResponse.json({
      message: "Grievance submitted successfully",
      complaint: {
        id: complaintId,
        trackingId: realTrackingId,
        title,
        status: trustScore >= 60.0 ? "SUBMITTED" : "TPA_REVIEW",
        trustScore,
        verificationResult,
        explainableReport
      }
    });

  } catch (error: any) {
    return NextResponse.json(
      { message: error.message || "Internal Server Error" },
      { status: 500 }
    );
  }
}
